/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school_management_system;

import java.sql.Date;
import java.util.*;
import javax.swing.JOptionPane;
import static school_management_system.Teacher.*;


/**
 *
 * @author Akul
 */
public class UpdateTeacher extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTeacher
     */
    
    HashMap<String,ArrayList<String>> courseMap = Course.getCourseList();
    ArrayList<String> courselist = new ArrayList<String>(courseMap.keySet());
    
    public UpdateTeacher() {
        initComponents();
        
        String str = " ";
        
        for(int j = 0; j<courselist.size();j++){
            str = str.concat(courselist.get(j));
            str = str.concat(",");
        }
        
        String[] CourseIDs = str.split(",");
        C3.setModel(new javax.swing.DefaultComboBoxModel<>(CourseIDs));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        R1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        R2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        R3 = new javax.swing.JRadioButton();
        T3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        A2 = new javax.swing.JTextArea();
        C3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        C1 = new javax.swing.JComboBox<>();
        C2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        U1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        A1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        P1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(R1);
        R1.setText("Yes");

        jLabel5.setText("Student  BDAY");

        buttonGroup1.add(R2);
        R2.setText("Virgin");

        jLabel6.setText("Teacher Course");

        buttonGroup1.add(R3);
        R3.setText("A Lot");

        A2.setColumns(20);
        A2.setRows(5);
        jScrollPane2.setViewportView(A2);

        jLabel7.setText("Student Sex");

        C1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        C2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel1.setText("STUDENT NAME");

        U1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U1ActionPerformed(evt);
            }
        });

        A1.setColumns(20);
        A1.setRows(5);
        jScrollPane1.setViewportView(A1);

        jLabel2.setText("Student Pass");

        jLabel9.setText("UUID");

        jLabel3.setText("Teacher Standards");
        jLabel3.setToolTipText("Enter CourseID");

        jButton2.setText("Get Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Student Address");

        jLabel8.setText("Student Email");

        jLabel10.setText("Teacher Salary");

        jLabel11.setText("Attendence");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(80, 80, 80)
                        .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                .addComponent(T1))
                                            .addComponent(U1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(26, 26, 26))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(228, 228, 228)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(U1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R1)
                            .addComponent(jLabel7)
                            .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(R2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(R3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(89, 89, 89))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int x = 0;

        boolean b = new Teacher(UUID.fromString(U1.getText()),null,null,null,
                                ' ',null,null,null,null,0.0,0).inTeacherList();

        ArrayList<Integer> stdlist = new ArrayList<>();
        

        int std = 0;

        if(!b){
            JOptionPane.showMessageDialog(this,"Invalid UUID");
            U1.setText("");
            T1.setText(" ");
            T2.setText(" ");
            T3.setText(" ");
            T4.setText(" ");
            T5.setText(" ");
            P1.setText("");
            A1.setText(" ");
            A2.setText(" ");
            C1.setSelectedIndex(0);
            C2.setSelectedIndex(0);
            C3.setSelectedIndex(0);
            R1.setSelected(true);
       }

       else{

        char sex = 'M';
        int month = 1;

        UUID uuid = UUID.fromString(U1.getText());

        String courseID = (String) C3.getSelectedItem();
        
        if(R1.isSelected()){
            sex ='M';
        }
        else if(R2.isSelected()){
            sex = 'F';
        }
        else if(R3.isSelected()){
            sex = 'O';
        }
        else{
            x = 1;
            JOptionPane.showMessageDialog(this,"Invalid Sex");
        }

        String[] stdstr = A2.getText().trim().split(",");
        
        stdlist = getStdNo(stdstr);

        switch((String)C2.getSelectedItem()){

            case "January"  :month = 1; break;
            case "February" :month = 2; break;
            case "March"    :month = 3; break;
            case "April"    :month = 4; break;
            case "May"      :month = 5; break;
            case "June"     :month = 6; break;
            case "July"     :month = 7; break;
            case "August"   :month = 8; break;
            case "September":month = 9; break;
            case "October"  :month = 10;break;
            case "November" :month = 11;break;
            case "December" :month = 12;break;
            default:
            x = 1;
            JOptionPane.showMessageDialog(this,"Incorrect Month");
        }

        String datestr = T2.getText() + "-" +
        month + "-" +
        (String)C1.getSelectedItem();

        Date date = Date.valueOf(datestr);
        
        double salary = Double.parseDouble(T4.getText());

        Teacher upteacher = new Teacher(uuid,T1.getText().trim(),P1.getText().trim(),
                                      date,sex,A1.getText().trim(),T3.getText().trim(),
                                      courseID,stdlist,salary,Integer.parseInt(T5.getText()));

        //Get the concerned teacher

        boolean c = upteacher.inTeacherList();

        if(!c){
            int ans = JOptionPane.showConfirmDialog(this,"Teacher doesn't exist. Add Teacher?");

            if(ans == 0){

                int radio  = 0;

                if(R1.isSelected()){
                    radio = 1;
                }
                else if(R2.isSelected()){
                    radio = 2;
                }
                else if(R3.isSelected()){
                    radio = 3;
                }

                new AddTeacher(T1.getText(),P1.getText(),C1.getSelectedIndex(),
                    C2.getSelectedIndex(),T2.getText(),courseID,radio,T4.getText(),
                    A1.getText(),T3.getText(),A2.getText()).setVisible(true);
                this.dispose();
            }
            else if(ans == 2) {
                this.dispose();
            }
            else if(ans == 1){
                U1.setText(" ");
                T1.setText(" ");
                T2.setText(" ");
                T3.setText(" ");
                T4.setText(" ");
                T5.setText(" ");
                P1.setText("");
                A1.setText(" ");
                A2.setText(" ");
                C1.setSelectedIndex(0);
                C2.setSelectedIndex(0);
                C3.setSelectedIndex(0);
                R1.setSelected(true);
            }
        }
        //Write it to file
        else if(x == 0){
            upteacher.replaceTeacher(uuid.toString());
            JOptionPane.showMessageDialog(this,"Data Successfully Updated");
            U1.setText(" ");
            T1.setText(" ");
            T2.setText(" ");
            T3.setText(" ");
            T4.setText(" ");
            T5.setText(" ");
            P1.setText("");
            A1.setText(" ");
            A2.setText(" ");
            C1.setSelectedIndex(0);
            C2.setSelectedIndex(0);
            C3.setSelectedIndex(0);
            R1.setSelected(true);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void U1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U1ActionPerformed

    }//GEN-LAST:event_U1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        

        boolean d = new Teacher(UUID.fromString(U1.getText()),null,null,null,
                                ' ',null,null,null,null,0.0,0).inTeacherList();


            if(d){
                Teacher teacher = new Teacher(UUID.fromString(U1.getText()));

                T1.setText(teacher.getUsername());
                P1.setText(teacher.getPass());

                String strdate = String.valueOf(teacher.getBDay());
                String[] date = strdate.split("-");
                C1.setSelectedIndex(Integer.parseInt(date[2])-1);
                C2.setSelectedIndex(Integer.parseInt(date[1])-1);
                T2.setText(date[0]);

                C3.setSelectedItem(teacher.getCourseID());

                switch(teacher.getSex()){
                    case 'M' :R1.setSelected(true); break;
                    case 'F' :R2.setSelected(true); break;
                    case 'O' :R3.setSelected(true); break;
                    default: System.out.print("error");
                }

                A1.setText(teacher.getAddress());
                T3.setText(teacher.getEmail());

                ArrayList<Integer> stdlist = teacher.getStdList();

                A2.setText("");
                
                for(int j = 0;j<stdlist.size();j++){
                A2.append(convertStd(stdlist.get(j)));
                A2.append(",");
            }

                T4.setText(Double.toString(teacher.getSalary()));   
                T5.setText(Integer.toString(teacher.getAttendence()));
            }
        

        else{
            int ans = JOptionPane.showConfirmDialog(this,"Teacher doesn't exist. Add Teacher?");

            if(ans == 0){

                int radio  = 0;

                if(R1.isSelected()){
                    radio = 1;
                }
                else if(R2.isSelected()){
                    radio = 2;
                }
                else if(R3.isSelected()){
                    radio = 3;
                }

                new AddTeacher(T1.getText(),P1.getText(),C1.getSelectedIndex(),
                    C2.getSelectedIndex(),T2.getText(),(String)C3.getSelectedItem(),radio,T4.getText(),
                    A1.getText(),T3.getText(),A2.getText()).setVisible(true);
                this.dispose();
            }
            else if(ans == 2) {
                this.dispose();
            }
            else if(ans == 1){
                U1.setText(" ");
                T1.setText(" ");
                T2.setText(" ");
                T3.setText(" ");
                T4.setText(" ");
                T5.setText(" ");
                P1.setText("");
                A1.setText(" ");
                A2.setText(" ");
                C1.setSelectedIndex(0);
                C2.setSelectedIndex(0);
                C3.setSelectedIndex(0);
                R1.setSelected(true);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Teacher.closeTeacherFile();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea A1;
    private javax.swing.JTextArea A2;
    private javax.swing.JComboBox<String> C1;
    private javax.swing.JComboBox<String> C2;
    private javax.swing.JComboBox<String> C3;
    private javax.swing.JPasswordField P1;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField U1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
